apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: haproxy
  rules:
    - host: ktse.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ktse
                port:
                  number: 8080
    - host: keruta.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ktcl-front-svc
                port:
                  number: 3000
    - host: ktcl-k8s.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ktcl-k8s
                port:
                  number: 8081
