# Option 1: Bitwarden Secrets Manager (ネイティブプロバイダー)
# Bitwarden Secrets Manager を使用する場合（有料プランが必要）
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardenSecretsManager:
      apiURL: https://api.bitwarden.com  # または https://api.bitwarden.eu
      identityURL: https://identity.bitwarden.com  # または https://identity.bitwarden.eu
      bitwardenServerSDKURL: https://vault.bitwarden.com  # または自己ホスト URL
      organizationID: "your-organization-id"  # TODO: Organization ID を設定
      auth:
        secretRef:
          name: bitwarden-secrets-manager-token
          namespace: external-secrets-system
          key: token
---
# Bitwarden Secrets Manager のアクセストークンを格納する Secret
# このファイルはサンプルです。実際の Secret は手動で作成してください。
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-secrets-manager-token
  namespace: external-secrets-system
type: Opaque
stringData:
  token: ""  # ここに Bitwarden Secrets Manager の Machine Account Token を設定
---
# 使用例: ExternalSecret
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: example-secret
#   namespace: default
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: bitwarden-secretsmanager
#     kind: ClusterSecretStore
#   target:
#     name: example-secret
#     creationPolicy: Owner
#   data:
#     - secretKey: password
#       remoteRef:
#         key: "339062b8-a5a1-4303-bf1d-b1920146a622"  # Secret の UUID
#         property: "value"  # 取得するフィールド
