apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    webhook:
      url: "http://bitwarden-sdk-server.external-secrets-system.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.password"
      secrets:
        - name: bw-token
          secretRef:
            name: bitwarden-cli-credentials
            namespace: external-secrets-system
            key: BW_PASSWORD
      headers:
        Content-Type: application/json
      body: |
        {
          "id": "{{ .remoteRef.key }}"
        }
---
# Bitwarden CLI を実行する Pod
# ESO が Bitwarden にアクセスするための SDK サーバー
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-sdk-server
  namespace: external-secrets-system
  labels:
    app: bitwarden-sdk-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden-sdk-server
  template:
    metadata:
      labels:
        app: bitwarden-sdk-server
    spec:
      containers:
        - name: bitwarden-sdk
          # Bitwarden SDK Server イメージ
          # 参考: https://github.com/lazyorangejs/bitwarden-sdk-server
          image: docker.io/lazyorange/bitwarden-sdk-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
              name: http
          env:
            - name: BW_HOST
              value: "https://vault.bitwarden.com"  # または独自の Bitwarden サーバー
            - name: BW_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: bitwarden-cli-credentials
                  key: BW_CLIENTID
            - name: BW_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: bitwarden-cli-credentials
                  key: BW_CLIENTSECRET
            - name: BW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bitwarden-cli-credentials
                  key: BW_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden-sdk-server
  namespace: external-secrets-system
spec:
  selector:
    app: bitwarden-sdk-server
  ports:
    - port: 8087
      targetPort: 8087
      name: http
