apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: ai-scheduler-db
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: ai-scheduler-db
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "f31f2f28-0233-4f3b-835f-b4d500cf5be1"
      secretKeyName: root-pass
    - bwSecretId: "3f523695-0d2a-4910-aa74-b4d500cf68e5"
      secretKeyName: pass
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: ai-scheduler-db
spec:
  rootPasswordSecretKeyRef:
    name: ai-scheduler-db
    key: root-pass
  image: mariadb:11
  port: 3306
  updateStrategy:
    autoUpdateDataPlane: true
  startupProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 60
  storage:
    size: 1Gi
    storageClassName: rook-ceph-rbd
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: ai-scheduler
spec:
  mariaDbRef:
    name: ai-scheduler-db
  name: ai_scheduler
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: ai-scheduler
spec:
  mariaDbRef:
    name: ai-scheduler-db
  passwordSecretKeyRef:
    name: ai-scheduler-db
    key: pass
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: ai-scheduler
spec:
  mariaDbRef:
    name: ai-scheduler-db
  privileges:
    - "ALL PRIVILEGES"
  database: ai_scheduler
  table: "*"
  username: ai-scheduler
  grantOption: false
