
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keruta-svc
  labels:
    app: keruta
spec:
  rules:
    - host: keruta.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keruta-svc
                port:
                  number: 80
