apiVersion: apps/v1
kind: Deployment
metadata:
  name: keruta-admin
  labels:
    app: keruta-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keruta-admin
  template:
    metadata:
      name: keruta-admin
      labels:
        app: keruta-admin
    spec:
      containers:
        - name: keruta-admin
          image: harbor.kigawa.net/library/keruta-admin:main-40cd4ae2043d9c08a3a7768a5301f9d2b55fd967
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              port: 3000
              path: /
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: KEYCLOAK_URL
              value: https://user.kigawa.net
            - name: KEYCLOAK_REALM
              value: manage
            - name: API_URL
              value: http://keruta-svc:8080
            - name: PUBLIC_API_URL
              value: https://keruta-api.kigawa.net
      restartPolicy: Always
