apiVersion: apps/v1
kind: Deployment
metadata:
  name: keruta-executor
  labels:
    app: keruta-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keruta-executor
  template:
    metadata:
      name: keruta-executor
      labels:
        app: keruta-executor
    spec:
      serviceAccountName: keruta-sa
      containers:
        - name: keruta-executor
          image: harbor.kigawa.net/library/keruta-executor:main-12ca041faaf2e9a11abd2c1a996259c54542e12b
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              port: 8081
              path: /actuator/health
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb-svc
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: keruta
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mongo
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: mongo
            - name: KERUTA_EXECUTOR_API_BASE_URL
              value: "http://keruta-svc:8080"
            - name: KERUTA_EXECUTOR_PROCESSING_DELAY
              value: "10000"
            - name: KERUTA_EXECUTOR_CODER_COMMAND
              value: "coder"
            - name: KERUTA_EXECUTOR_CODER_WORKING_DIR
              value: "/tmp/coder"
            - name: KERUTA_EXECUTOR_CODER_TIMEOUT
              value: "1800000"
      restartPolicy: Always
