apiVersion: apps/v1
kind: Deployment
metadata:
  name: keruta
  labels:
    app: keruta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keruta
  template:
    metadata:
      name: keruta
      labels:
        app: keruta
    spec:
      serviceAccountName: keruta-sa
      containers:
        - name: keruta
          image: harbor.kigawa.net/library/keruta:main-3fea5c12b85f4be3d9a66742fec4798f929d4333
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              port: 8080
              path: /api/health
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KEYCLOAK_URL
              value: https://user.kigawa.net
            - name: KEYCLOAK_REALM
              value: manage
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: keycloak
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb-svc
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: keruta
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mongo
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: mongo
      restartPolicy: Always
