apiVersion: v1
kind: ServiceAccount
metadata:
  name: keruta-sa
  namespace: kigawa-net-keruta
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: kigawa-net-keruta
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keruta-pod-creator
  namespace: kigawa-net-keruta
subjects:
- kind: ServiceAccount
  name: keruta-sa
  namespace: kigawa-net-keruta
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io