apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: arc-github-secret-bws
  namespace: arc-runners
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: arc-github-secret
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "<APP_ID_SECRET_ID>"
      secretKeyName: github_app_id
    - bwSecretId: "<INSTALLATION_ID_SECRET_ID>"
      secretKeyName: github_app_installation_id
    - bwSecretId: "<PRIVATE_KEY_SECRET_ID>"
      secretKeyName: github_app_private_key
