apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: arc-github-secret-bws
  namespace: arc-runners
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: arc-github-secret
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "508b0d73-19a4-4890-9051-b45e002a8a53"
      secretKeyName: github_app_id
    - bwSecretId: "725d764f-d535-423e-916f-b45e002c3988"
      secretKeyName: github_app_installation_id
    - bwSecretId: "39afc372-603a-4644-9ca5-b45e002b0b30"
      secretKeyName: github_app_private_key
