apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: arc-github-secret-kigawa-net-bws
  namespace: arc-runners
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: arc-github-secret-kigawa-net
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "68d9ea2d-0454-4c86-ba16-b46c0047fb13"
      secretKeyName: github_app_id
    - bwSecretId: "0b1c6b8a-ab19-4e3b-a17e-b47100c7abb2"
      secretKeyName: github_app_installation_id
    - bwSecretId: "03655c46-729c-4410-b30c-b46c0049a381"
      secretKeyName: github_app_private_key
