apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: ktcl-k8s-bws
  namespace: kigawa-net-keruta-dev
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: ktcl-k8s-sec
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "217aa846-8d1f-4f3c-8dbf-b4000066c764"
      secretKeyName: private-key
