apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktse-dev
  namespace: kigawa-net-keruta-dev
  labels:
    app: ktse-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktse-dev
  template:
    metadata:
      name: ktse-dev
      labels:
        app: ktse-dev
    spec:
      serviceAccountName: keruta-dev-sa
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: ktse-dev
          image: harbor.kigawa.net/library/ktse:develop-c6574bd09617be9708307e5dd82300f3c38c2a71
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: PROVIDER_0_NAME
              value: web
            - name: PROVIDER_0_AUDIENCE
              value: keruta
            - name: PROVIDER_0_ISSUER
              value: https://keruta-dev.kigawa.net
            - name: IDP_0_AUDIENCE
              value: keruta
            - name: IDP_0_ISSUER
              value: https://user.kigawa.net/realms/develop
            - name: DB_JDBC_URL
              value: jdbc:mysql://keruta-dev-tidb-tidb:4000/keruta
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: tidb
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: tidb
            - name: ZK_HOST
              value: zk-svc:2181
      restartPolicy: Always
