apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktse-dev
  namespace: kigawa-net-keruta-dev
  labels:
    app: ktse-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktse-dev
  template:
    metadata:
      name: ktse-dev
      labels:
        app: ktse-dev
    spec:
      serviceAccountName: keruta-dev-sa
      containers:
        - name: ktse-dev
          image: harbor.kigawa.net/library/ktse:develop-b5e30254a3db6d79f61bf9eaf00bd997e23d3a6b
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PROVIDER_0_NAME
              value: web
            - name: PROVIDER_0_AUDIENCE
              value: keruta
            - name: PROVIDER_0_ISSUER
              value: https://keruta-dev.kigawa.net/
            - name: IDP_0_AUDIENCE
              value: keruta
            - name: IDP_0_ISSUER
              value: https://user.kigawa.net/realms/develop
            - name: DB_JDBC_URL
              value: jdbc:mysql://tidb-cluster-tidb.tidb-system.svc.cluster.local:4000/keruta
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: tidb
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: tidb
            - name: ZK_HOST
              value: zk-client-svc:2181
      restartPolicy: Always
