apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: mariadb-ktse
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: mariadb-ktse
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "c15a90e2-60d5-45e3-8e0b-b40a00ed5136"
      secretKeyName: root-pass
    - bwSecretId: "320e05ff-154e-4797-b4c3-b3e2000fdd1c"
      secretKeyName: pass
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-ktse
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-ktse
    key: root-pass
  image: mariadb:10.11
  port: 3306
  updateStrategy:
    autoUpdateDataPlane: true
  startupProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 60
  storage:
    size: 1Gi
    storageClassName: rook-ceph-rbd
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: mariadb-ktse
spec:
  mariaDbRef:
    name: mariadb-ktse
  name: mariadb-ktse
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: mariadb-ktse
spec:
  mariaDbRef:
    name: mariadb-ktse
  passwordSecretKeyRef:
    name: mariadb-ktse
    key: pass
  maxUserConnections: 50
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: mariadb-ktse
spec:
  mariaDbRef:
    name: mariadb-ktse
  privileges:
    - "ALL PRIVILEGES"
  database: mariadb-ktse
  table: "*"
  username: mariadb-ktse
  grantOption: false