apiVersion: v1
kind: ServiceAccount
metadata:
  name: keruta-sa
  namespace: kigawa-net-keruta-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: kigawa-net-keruta-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keruta-pod-creator
  namespace: kigawa-net-keruta-dev
subjects:
- kind: ServiceAccount
  name: keruta-sa
  namespace: kigawa-net-keruta-dev
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
