apiVersion: v1
kind: Namespace
metadata:
  name: kigawa-net-keruta-dev-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox
  namespace: kigawa-net-keruta-dev-sandbox
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox
  namespace: kigawa-net-keruta-dev-sandbox
subjects:
  - kind: ServiceAccount
    name: ktcl-k8s
    namespace: kigawa-net-keruta-dev
roleRef:
  kind: Role
  name: sandbox
  apiGroup: rbac.authorization.k8s.io