apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: keruta-dev-tidb
  namespace: kigawa-net-keruta-dev
spec:
  version: v8.5.2
  timezone: Asia/Tokyo
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate

  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 3
    requests:
      storage: "10Gi"
    config: |
      [log]
      level = "info"
    storageClassName: rook-cephfs
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 0.5Gi
    initContainers:
    - name: pd-data-check
      image: busybox:1.36
      command:
      - sh
      - -c
      - |
        DB="/var/lib/pd/member/snap/db"
        if [ ! -f "$DB" ]; then
          echo "No database file, skipping check"
          exit 0
        fi
        # bbolt マジックバイト確認 (0xED0CDAED little-endian = ED DA 0C ED)
        MAGIC=$(od -A n -t x1 -N 4 "$DB" | tr -d ' \n')
        if [ "$MAGIC" = "edda0ced" ]; then
          echo "Database valid (magic=$MAGIC)"
        else
          echo "Corrupted database detected (magic=$MAGIC), removing member data for recovery"
          rm -rf /var/lib/pd/member
        fi
      volumeMounts:
      - name: pd
        mountPath: /var/lib/pd

  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: 1
    requests:
      storage: "20Gi"
    config: |
      [log]
      level = "info"
    storageClassName: rook-cephfs
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi

  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 1
    service:
      type: ClusterIP
      annotations: {}
    config: |
      [log]
      level = "info"
      [performance]
      max-procs = 0
      tcp-keep-alive = true
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
