apiVersion: v1
kind: Service
metadata:
  name: zk-server-svc
  labels:
    app: zk-pod
spec:
  clusterIP: None
  selector:
    app: zk-pod
  ports:
    - name: server
      port: 2888
    - name: leader-election
      port: 3888
