apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk-sts
spec:
  serviceName: zk-svc
  replicas: 3
  selector:
    matchLabels:
      app: zk-pod
  template:
    metadata:
      labels:
        app: zk-pod
    spec:
      containers:
        - name: zk-con
          image: zookeeper:3.9
          command:
            - sh
            - -c
            - |
              ORDINAL=${HOSTNAME##*-}
              export ZOO_MY_ID=$((ORDINAL + 1))
              exec /docker-entrypoint.sh zkServer.sh start-foreground

          env:
            - name: ZOO_SERVERS
              value: >
                server.1=zk-sts-0.zk-svc.kigawa-net-keruta-dev.svc.cluster.local:2888:3888
                server.2=zk-sts-1.zk-svc.kigawa-net-keruta-dev.svc.cluster.local:2888:3888
                server.3=zk-sts-2.zk-sts-2.zk-svc.kigawa-net-keruta-dev.svc.cluster.local:2888:3888
            - name: ZOO_CLIENT_PORT
              value: "2181"
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "*"

          ports:
            - name: client
              containerPort: 2181
            - name: server
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/zookeeper/data
            - name: datalog
              mountPath: /var/lib/zookeeper/log
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: "rook-ceph-rbd"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: datalog
      spec:
        storageClassName: "rook-ceph-rbd"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
