apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ktcl-front
  namespace: kigawa-net-keruta-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ktcl-front
    creationPolicy: Owner
  data:
    - secretKey: private-key
      remoteRef:
        key: "<uuid-of-ktcl-front-private-key>"  # TODO: Bitwarden Secrets Manager の Secret UUID に置換
        property: "value"
---
# Bitwarden Secrets Manager での設定:
#
# 1. Organization → Secrets Manager にアクセス
# 2. Secret を作成:
#    - Name: keruta-dev-ktcl-front-private-key
#    - Value: <JWT signing private key>
#      ※複数行のキーも直接貼り付け可能
# 3. Secret の UUID をコピー（右上の ID ボタン）
# 4. 上記の <uuid-of-xxx-secret> を実際の UUID に置換
