apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ktcl-front
  namespace: kigawa-net-keruta-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: ktcl-front
    creationPolicy: Owner
  data:
    - secretKey: private-key
      remoteRef:
        key: keruta-dev-ktcl-front-private-key  # Bitwarden item ID
---
# Bitwarden での設定方法:
# 1. Bitwarden に以下の項目を作成:
#    - 名前: keruta-dev-ktcl-front-private-key
#      パスワード: <JWT signing private key>
# 2. 長いキーの場合は Notes フィールドに保存し、remoteRef.property を使用:
#    remoteRef:
#      key: keruta-dev-ktcl-front-private-key
#      property: notes
