apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tidb
  namespace: kigawa-net-keruta-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: tidb
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: keruta-dev-tidb-user  # Bitwarden item ID または名前
    - secretKey: pass
      remoteRef:
        key: keruta-dev-tidb-pass  # Bitwarden item ID または名前
---
# Bitwarden での設定方法:
# 1. Bitwarden に以下の項目を作成:
#    - 名前: keruta-dev-tidb-user
#      パスワード: <TiDB username>
#    - 名前: keruta-dev-tidb-pass
#      パスワード: <TiDB password>
# 2. この ExternalSecret を適用すると、自動的に Secret "tidb" が作成されます
