
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keruta-dev-ingress
  namespace: kigawa-net-keruta-dev
spec:
  ingressClassName: haproxy
  rules:
    - host: keruta-dev-api.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keruta-dev-svc
                port:
                  number: 8080
    - host: keruta-dev.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keruta-dev-admin-svc
                port:
                  number: 3000
