apiVersion: apps/v1
kind: Deployment
metadata:
  name: keruta-dev
  namespace: kigawa-net-keruta-dev
  labels:
    app: keruta-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keruta-dev
  template:
    metadata:
      name: keruta-dev
      labels:
        app: keruta-dev
    spec:
      serviceAccountName: keruta-dev-sa
      containers:
        - name: keruta-dev
          image: harbor.kigawa.net/library/keruta-api:develop-f1d2064ed0fb830b06608ee0f9a644d78fa01766
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              port: 8080
              path: /api/v1/health
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KEYCLOAK_URL
              value: https://user.kigawa.net
            - name: KEYCLOAK_REALM
              value: manage
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: keycloak
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb-svc
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: keruta
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mongo
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: app-secret
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: mongo
            - name: AUTH_API_USERNAME
              value: "keruta-api"
            - name: AUTH_ADMIN_USERNAME
              value: "admin"
            - name: SPRING_WEB_CORS_ALLOWED_ORIGINS
              value: "http://localhost:3000,https://keruta-dev.kigawa.net"
            - name: SPRING_WEB_CORS_ALLOWED_METHODS
              value: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
            - name: SPRING_WEB_CORS_ALLOWED_HEADERS
              value: "Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers"
            - name: SPRING_WEB_CORS_ALLOW_CREDENTIALS
              value: "true"
            - name: SPRING_WEB_CORS_MAX_AGE
              value: "3600"
            - name: SPRING_WEB_CORS_SPECIFIC_ORIGINS
              value: "http://localhost:3000,http://localhost:3001,https://keruta-dev.kigawa.net"
            # Coder Integration Configuration
            - name: CODER_BASE_URL
              value: "https://coder.kigawa.net"
            - name: CODER_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  key: session-token
                  name: coder
            - name: CODER_ORGANIZATION
              value: "default"
            - name: CODER_USER
              value: "admin"
            - name: CODER_DEFAULT_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  key: default-template-id
                  name: coder
                  optional: true
            - name: CODER_CONNECTION_TIMEOUT
              value: "10000"
            - name: CODER_READ_TIMEOUT
              value: "30000"
            - name: CODER_ENABLE_SSL_VERIFICATION
              value: "true"
            # keruta Executor Configuration
            - name: keruta_EXECUTOR_BASE_URL
              value: "http://keruta-dev-executor-svc:8080"
      restartPolicy: Always
