apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: sentry-bws
  namespace: kigawa-net-sentry
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: sentry-sec
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "TODO: replace with Bitwarden secret ID for sentry admin-password"
      secretKeyName: admin-password
    - bwSecretId: "TODO: replace with Bitwarden secret ID for sentry system-secret-key"
      secretKeyName: system-secret-key
