apiVersion: batch/v1
kind: Job
metadata:
  name: snuba-run-migration
  namespace: kigawa-net-sentry
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/getsentry/snuba:26.5.0
          command:
            - snuba
            - migrations
            - migrate
            - --force
          env:
            - name: SNUBA_SETTINGS
              value: /etc/snuba/settings.py
            - name: DEFAULT_BROKERS
              value: sentry-kafka:9092
            - name: KAFKA_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: CLICKHOUSE_MAX_CONNECTIONS
              value: "100"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: config
              mountPath: /etc/snuba
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: sentry-snuba
