apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: keruta-dev-tidb
  namespace: kigawa-net-keruta-dev
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: tidb
  authToken:
    secretName: bw-auth-token
    secretKey: token
    secretNamespace: sm-operator-system
  map:
    - bwSecretId: "29f7c712-30b5-477b-82d7-b3e2000fb915"
      secretKeyName: user
    - bwSecretId: "320e05ff-154e-4797-b4c3-b3e2000fdd1c"
      secretKeyName: pass