apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: keruta-dev-tidb
  namespace: kigawa-net-keruta-dev
spec:
  organizationId: "<YOUR_ORGANIZATION_ID>"
  secretName: tidb
  authToken:
    secretName: bw-auth-token
    secretKey: token
    secretNamespace: sm-operator-system
  map:
    - bwSecretId: "<TIDB_USER_SECRET_UUID>"
      secretKeyName: user
    - bwSecretId: "<TIDB_PASS_SECRET_UUID>"
      secretKeyName: pass