apiVersion: batch/v1
kind: CronJob
metadata:
  name: bitwarden-sync-crn
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          serviceAccountName: sec-sync-sa
          restartPolicy: OnFailure
          containers:
            - name: create-secret
              env:
                - name: TARGET_NAMESPACES
                  value: |
                    kigawa-net-keruta-dev
                    kigawa-net-keruta-main
                    kigawa-net-lp-main
                    kigawa-net-nextcloud
                    develop
                    kigawa-net-maas
                    kigawa-net-mc-ftb-mc
                    kigawa-net-llm
                    kigawa-net-llm-proxy
                    kigawa-net-llm-ui
                    keycloak
                    arc-runners
                    kigawa-net-sentry
                    kigawa-net-mamoru-main
                    mcp-discord
                    mcp-growi
                    onemc-rpgcore
                    onemc-rpgcore-stg
                    onemc-rpgcore-dev
                    onemc-build
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - -c
                - |
                  set -e

                  token=$(kubectl get secret bitwarden-sec -o jsonpath='{.data.token}' | base64 -d)

                  echo "$TARGET_NAMESPACES" | while read -r namespace; do
                    if [[ -z "$namespace" ]]; then continue; fi
                    kubectl create secret generic bitwarden-sec \
                      --from-literal=token="$token" \
                      --dry-run=client -o yaml -n "$namespace" | kubectl apply -f -

                    echo "Secret bitwarden-sec synced successfully at $(date) to $namespace"
                  done
