apiVersion: batch/v1
kind: CronJob
metadata:
  name: harbor-sync-crn
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          serviceAccountName: sec-sync-sa
          restartPolicy: OnFailure
          containers:
            - name: create-secret
              env:
                - name: TARGET_NAMESPACES
                  value: |
                    kigawa-net-keruta-dev
                    develop
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - -c
                - |
                  set -e

                  # Read username and password from source secret
                  USERNAME=$(kubectl get secret harbor-sec -o jsonpath='{.data.user}' | base64 -d)
                  PASSWORD=$(kubectl get secret harbor-sec -o jsonpath='{.data.pass}' | base64 -d)
                  
                  echo "$TARGET_NAMESPACES" | while read -r namespace; do
                    # Create or update the harbor-registry secret with correct type
                    kubectl create secret docker-registry harbor-registry \
                      --docker-server=harbor.kigawa.net \
                      --docker-username="$USERNAME" \
                      --docker-password="$PASSWORD" \
                      --dry-run=client -o yaml -n "$namespace" | kubectl apply -f -
  
                    echo "Secret harbor-registry synced successfully at $(date) to $namespace"
                  done
  
