
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sec-sync-cro
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]