FROM ubuntu:22.04

ARG MAAS_VERSION=3.5

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        software-properties-common && \
    add-apt-repository -y ppa:maas/${MAAS_VERSION} && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        maas-rack-controller && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint-rack.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]