apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners-onemc
  namespace: argocd
spec:
  project: kigawa-net

  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.9.3
    helm:
      releaseName: arc-runner-set
      valuesObject:
        githubConfigUrl: "https://github.com/OneServerMC"
        githubConfigSecret: arc-github-secret
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-gha-rs-controller
        containerMode:
          type: dind
        minRunners: 0
        maxRunners: 5
        template:
          spec:
            containers:
              - name: runner
                resources:
                  requests:
                    memory: "4Gi"
                    cpu: "2"
                    ephemeral-storage: "20Gi"
                  limits:
                    memory: "8Gi"
                    cpu: "4"
                    ephemeral-storage: "30Gi"

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners

  ignoreDifferences:
    - group: actions.github.com
      kind: AutoscalingListener
    - group: rbac.authorization.k8s.io
      kind: Role
      labelMatchExpressions:
        - key: app.kubernetes.io/component
          operator: In
          values: [runner-scale-set-listener]
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      labelMatchExpressions:
        - key: app.kubernetes.io/component
          operator: In
          values: [runner-scale-set-listener]

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
