apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners-onemc
  namespace: argocd
spec:
  project: kigawa-net

  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.9.3
    helm:
      releaseName: arc-runner-set
      valuesObject:
        githubConfigUrl: "https://github.com/OneServerMC"
        githubConfigSecret: arc-github-secret
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-gha-rs-controller
        containerMode:
          type: dind
        minRunners: 0
        maxRunners: 5
        template:
          spec:
            initContainers:
              - name: init-dind-externals
                image: ghcr.io/actions/actions-runner:2.321.0
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:2.321.0
                resources:
                  requests:
                    memory: "4Gi"
                    cpu: "2"
                    ephemeral-storage: "20Gi"
                  limits:
                    memory: "8Gi"
                    cpu: "4"
                    ephemeral-storage: "30Gi"
              - name: dind
                image: docker:dind

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners

  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
