apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners-onemc
  namespace: argocd
spec:
  project: kigawa-net

  source:
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    targetRevision: 0.9.3
    helm:
      releaseName: arc-runner-set
      valuesObject:
        githubConfigUrl: "https://github.com/OneServerMC"
        githubConfigSecret: arc-github-secret
        containerMode:
          type: dind
        minRunners: 0
        maxRunners: 5
        template:
          spec:
            containers:
              - name: runner
                resources:
                  requests:
                    memory: "4Gi"
                    cpu: "2"
                    ephemeral-storage: "20Gi"
                  limits:
                    memory: "8Gi"
                    cpu: "4"
                    ephemeral-storage: "30Gi"

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
