apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  project: kigawa-net

  source:
    repoURL: https://github.com/kigawa-net/kigawa-net-k8s.git
    targetRevision: main
    path: coredns
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
