apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "0.9.11"
    helm:
      values: |
        installCRDs: true

        # ------------------------
        # Bitwarden SDK Server を有効化
        bitwarden-sdk-server:
          enabled: true

        # Webhook サーバー
        webhook:
          port: 9443

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kigawa-net/kigawa-net-k8s.git
    targetRevision: main
    path: external-secrets
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true