apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kigawa-net-keruta-dev-tidb-app
  namespace: argocd
spec:
  project: default
  # Prevent ArgoCD from adding its own instance label
  # which conflicts with Helm's release-based labeling
  trackingMethod: annotation

  source:
    repoURL: https://charts.pingcap.org/
    chart: tidb-cluster
    targetRevision: "v1.5.1"
    helm:
      releaseName: tidb-cluster
      valuesObject:
        schedulerName: default-scheduler
        version: v8.5.0
        pd:
          replicas: 1
          storageClassName: rook-cephfs
          storageSize: 10Gi
        tikv:
          replicas: 1
          storageClassName: rook-cephfs
          storageSize: 20Gi
        tidb:
          replicas: 1


  destination:
    server: https://kubernetes.default.svc
    namespace: tidb-system

  syncPolicy:
    automated:
      prune: true
