apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kigawa-net-nextcloud-cli-upgrade
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: kigawa-net

  source:
    repoURL: https://github.com/kigawa-net/kigawa-net-k8s.git
    targetRevision: main
    path: nextcloud-cli-upgrade
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kigawa-net-nextcloud

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
