apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: one
  namespace: argocd
spec:
  description: Project for OneServerMC resources

  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: onemc
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: onemc-*
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: one
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: onemc-rpgcore
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: onemc-rpgcore-stg
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: onemc-rpgcore-dev
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: onemc-build

  sourceRepos:
    - https://github.com/OneServerMC/*

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
