apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneserver-prod
  namespace: argocd
spec:
  project: one

  source:
    repoURL: https://github.com/OneServerMC/infra.git
    targetRevision: main
    path: one/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: onemc-rpgcore

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
