apiVersion: apps/v1
kind: Deployment
metadata:
  name: keruta-beta-executor
  namespace: kigawa-net-keruta-beta
  labels:
    app: keruta-beta-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keruta-beta-executor
  template:
    metadata:
      name: keruta-beta-executor
      labels:
        app: keruta-beta-executor
    spec:
      serviceAccountName: keruta-beta-sa
      containers:
        - name: keruta-beta-executor
          image: harbor.kigawa.net/library/keruta-executor:main-0cd5d6eee0849faf3c5792bb0ae66dc188dddf48
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              port: 8080
              path: /actuator/health
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb-svc
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: keruta
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mongo
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: mongo
            - name: KERUTA_EXECUTOR_API_BASE_URL
              value: "http://keruta-beta-svc:8080"
            - name: KERUTA_EXECUTOR_PROCESSING_DELAY
              value: "10000"
            - name: KERUTA_EXECUTOR_CODER_COMMAND
              value: "coder"
            - name: KERUTA_EXECUTOR_CODER_WORKING_DIR
              value: "/tmp/coder"
            - name: KERUTA_EXECUTOR_CODER_TIMEOUT
              value: "1800000"
            - name: KERUTA_EXECUTOR_CODER_BASE_URL
              value: "http://coder.kigawa-coder.svc.cluster.local:3000"
            - name: KERUTA_EXECUTOR_CODER_TOKEN
              valueFrom:
                secretKeyRef:
                  key: session-token
                  name: coder
                  optional: false
            - name: KERUTA_EXECUTOR_CODER_ENABLE_CLI_FALLBACK
              value: "true"
            - name: CODER_URL
              value: "http://coder.kigawa-coder.svc.cluster.local:3000"
            - name: CODER_TOKEN
              valueFrom:
                secretKeyRef:
                  key: session-token
                  name: coder
                  optional: true
      restartPolicy: Always
