apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oneserver-files
  namespace: kigawa-net-oneserver-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 20Gi
