apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: maas-secret
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: maas-secret
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "7c6fddef-9255-49c7-808d-b41500d36842"  # TODO: replace with actual Bitwarden secret ID for maas shared secret
      secretKeyName: secret