apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maas-postgres
spec:
  serviceName: maas-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: maas-postgres
  template:
    metadata:
      labels:
        app: maas-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: maas
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: maas-postgres
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: maas-postgres
                  key: pass
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "maas", "-d", "maas"]
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "maas", "-d", "maas"]
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-rbd
        resources:
          requests:
            storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: maas-postgres-svc
spec:
  selector:
    app: maas-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: maas-postgres
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: maas-postgres
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "e28802c4-9773-466e-b0d9-b41500c35113"  # TODO: replace with actual Bitwarden secret ID for mariadb root password
      secretKeyName: pass
    - bwSecretId: "376ad4b7-425e-40b1-85da-b41500c33f86"  # TODO: replace with actual Bitwarden secret ID for mariadb nextcloud user password
      secretKeyName: user