name: maas-build
on:
  push:
    branches:
      - main
    paths:
      - 'maas/docker/**'
  workflow_dispatch:

jobs:
  build-region:
    uses: ./.github/workflows/release.yml
    with:
      name: maas-region
      harborProject: library
      manifestFile: maas/region.yaml
      repository: kigawa-net/kigawa-net-k8s
      dockerFile: maas/docker/Dockerfile.region
      yamlPath: '.spec.template.spec.containers[0].image'
    secrets:
      HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

  build-rack:
    uses: ./.github/workflows/release.yml
    with:
      name: maas-rack
      harborProject: library
      manifestFile: maas/rack.yaml
      repository: kigawa-net/kigawa-net-k8s
      dockerFile: maas/docker/Dockerfile.rack
      yamlPath: '.spec.template.spec.containers[0].image'
    secrets:
      HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}